### ISSUE TITLE
Failure to build with gcc 4.8.4

### ISSUE THREAD

**Issue by keithj** [wtsi-npg/baton#148]
````
query.c: In function 'make_query_format_from_sql':
query.c:624:21: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     } else if (reti == REG_NOMATCH) {
                     ^
query.c:659:25: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         } else if (reti == REG_NOMATCH) {
                         ^
query.c:689:25: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
         } else if (reti == REG_NOMATCH) {

                         ^
query.c: In function 'prepare_specific_labels':
query.c:819:21: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
     } else if (reti == REG_NOMATCH) {
                     ^
````
